### ISSUE TITLE
Feature Request: Put Munki-Pkg on Pip

### ISSUE THREAD

**Issue by codekiln** [munki/munki-pkg#26]
It would be helpful to have munki-pkg available [through pip](https://pypi.python.org/pypi?%3Aaction=search&term=munki-pkg&submit=search) so we could list a certain version as a dependency to our projects.

**Comment by gregneagle** [comment]
No plans to do this.

**Comment by vatsalaggarwal** [comment]
https://github.com/munki/munki-pkg/pull/63 should help with this.
