### ISSUE TITLE
What is a "distribution-style" package?

### ISSUE THREAD

**Issue by pimlottc-gov** [munki/munki-pkg#29]
The documentation talks about the distribution_style flag but does not explain what a "distribution-style" package is, and I can't find any clear definition anywhere else in the munki documentation.

**Comment by gregneagle** [comment]
This is a style of _Apple_ package and therefore is outside of the scope/responsibility of munki-pkg (and Munki, a different tool) to document.

**Comment by pimlottc-gov** [comment]
Okay, so how about a link to an external doc?

**Comment by gregneagle** [comment]
If you find a helpful external documentation link, send it to me and I'll link to it in the wiki.

**Comment by pimlottc-gov** [comment]
Well, I found [this](https://developer.apple.com/legacy/library/documentation/DeveloperTools/Conceptual/SoftwareDistribution4/Managed_Installs/Managed_Installs.html#//apple_ref/doc/uid/TP40004615-CH6-DontLinkElementID_26), but there's a big warning that it's legacy documentation.  I'm just learning about all this so I'm not sure it's still valid.
