### ISSUE TITLE
Add Licensing to package

### ISSUE THREAD

**Issue by dikshas11** [munki/munki-pkg#51]
Is there a way to add licensing agreement and then asking user to install or uninstall the app. I started working on building packages today. 
If the package includes a license agreement file, Installer displays it in the License page. The user must accept the license in order to continue the installation process.

**Comment by gregneagle** [comment]
It’s not a lame question but probably beyond what you might expect the developer of this tool to explain/document.  This tool is a hammer. You might be able to build a house with it but house-building instructions don’t come with every hammer. 

I’d recommend you seek out articles, books, and documentation on Apple packages. One such is this book: https://scriptingosx.com/packaging-for-apple-administrators/

**Comment by dikshas11** [comment]
Thank you for the quick response.
