### ISSUE TITLE
strip .DS_Store files from scripts folder prior to package build

### ISSUE THREAD

**Issue by erikng** [munki/munki-pkg#9]
Per our conversation from yesterday, while .DS_Store files are probably harmless, it's aesthetically unpleasing to see these files in the scripts folder of a package.

**Comment by gregneagle** [comment]
Erik is referring to .DS_Store files in the _scripts_ folder and not the payload. Your PR would not address this.

**Comment by erikng** [comment]
Closing since this is fixed.
